version: '3.1'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - 3001:3000
    volumes:
      - .:/app
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8001:5432
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
