version: '3.1'
volumes:
  node_modules:
services:
  app:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 8001:5432
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
